In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h1>JonesKammen Dataset</h1>

In [26]:
jonesKammen = pd.read_excel('../../data/Jones-Kammen-2014-Zip-City-County-Results.xlsx', sheet_name='zip code results')
jonesKammen['State'].unique
jonesKammen_ca_zipcode = jonesKammen[(jonesKammen['State'] == 'CA') | (jonesKammen['State'] == 'TX')]
jonesKammen_ca_zipcode.head()

,ZipCode,Population,PersonsPerHousehold,AverageHouseValue,IncomePerHousehold,Latitude,Longitude,Elevation,State,StateFullName,...,FUELOIL (gallons),Vehicle miles traveled,Transport (tCO2e/yr),Housing (tCO2e/yr),Food (tCO2e/yr),Goods (tCO2e/yr),Services (tCO2e/yr),Total Household Carbon Footprint (tCO2e/yr),HouseholdsPerZipCode,Total Zip Code Carbon Footprint (tCO2e/yr)
24736,75001,8259,1.67,211500,57064,32.960001,-96.829187,463,TX,Texas,...,0.000000,19940,14.774988,8.851820,5.01,5.820733,7.020531,41.478072,5298,2.197508e+05
24737,75002,37216,3.04,134600,74144,33.087120,-96.616980,592,TX,Texas,...,0.000000,35597,24.736837,15.787862,9.12,7.408869,8.570391,65.623959,12643,8.296837e+05
24738,75006,46784,2.74,113100,52798,32.961400,-96.892100,463,TX,Texas,...,0.000000,24155,16.914721,12.096817,8.22,5.926129,6.706355,49.864023,17623,8.787537e+05
24739,75007,49933,2.88,127500,70081,33.006618,-96.890125,662,TX,Texas,...,0.182369,30477,21.462029,14.593276,8.64,7.094802,8.210965,60.001072,17652,1.059139e+06
24740,75009,4951,2.88,114400,52821,33.339100,-96.759300,592,TX,Texas,...,0.710305,34030,22.944477,14.438899,8.64,5.988365,6.717172,58.728913,1854,1.088834e+05

<h1> CoolClimate API Datasets </h1>

<h3>CoolClimate household 1 Dataset</h3>

In [29]:
coolClimate_household_1 = pd.read_csv('../../data/coolclimate-api-CAzips-singlehouseholds-withzc.csv')
X = coolClimate_household_1[['input_income', 'input_footprint_transportation_num_vehicles', 'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_1['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy


coolClimate_household_1 = data

coolClimate_household_1.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,1.0,1.0,22.0,8700.0,1.0,2.0,0.0,0.0,1085.39,1455.31,470.0,1591.0,237.0,543.0,169.350149,47.227769,55.002939,963.524289,90001.0,18.998752
1,1.0,1.0,22.0,8500.0,1.0,2.0,0.0,0.0,1085.39,1455.31,510.0,1591.0,237.0,543.0,161.234333,45.486592,51.436731,935.303780,90002.0,18.960587
2,1.0,1.0,22.0,8000.0,1.0,2.0,0.0,0.0,1085.39,1455.31,490.0,1591.0,237.0,543.0,157.543718,44.716724,49.867708,923.983913,90003.0,18.488686
3,1.0,1.0,22.0,7300.0,1.0,1.0,1.0,0.0,1085.39,1455.31,360.0,1591.0,237.0,543.0,133.502127,42.053263,45.315034,1012.205374,90004.0,18.001409
4,1.0,1.0,22.0,6000.0,1.0,4.0,0.0,0.0,1085.39,1455.31,310.0,1591.0,237.0,543.0,121.236910,38.452350,37.588628,902.778103,90005.0,16.311888

<h3>CoolClimate household 2 Dataset</h3>

In [30]:
coolClimate_household_1['input_footprint_housing_squarefeet'].value_counts()
#miles1

1591.0    136
1420.0    129
1689.0    119
1590.5    113
1419.0    109
1502.0    105
1993.0     98
1750.0     98
1854.0     95
2500.0     83
2217.0     83
Name: input_footprint_housing_squarefeet, dtype: int64

In [31]:
coolClimate_household_2 = pd.read_csv("../../data/coolclimate-api-CAzips-size2households-withzc.csv")
X = coolClimate_household_2[['input_income', 'input_footprint_transportation_num_vehicles', 'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_2['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy


coolClimate_household_2 = data
coolClimate_household_2.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,2.0,1.0,22.0,5200.0,1.0,1.0,2.0,0.0,1157.25,1627.91,510.0,1420.0,254.284,1086.0,201.317335,57.120956,41.800728,1108.236140,90025,21.750477
1,2.0,1.0,22.0,7900.0,1.0,4.0,0.0,0.0,1085.39,1455.31,520.0,1420.0,254.284,1086.0,201.421607,50.961077,33.028018,823.225480,90026,21.386459
2,2.0,1.0,22.0,7800.0,1.0,5.0,0.0,0.0,1085.39,1455.31,490.0,1420.0,254.284,1086.0,175.059119,48.370380,30.314787,864.610333,90027,21.337905
4,2.0,1.0,22.0,7000.0,1.0,3.0,0.0,0.0,1085.39,1455.31,460.0,1420.0,254.284,1086.0,188.142608,47.011820,27.896995,721.991028,90029,19.782698
5,2.0,1.0,22.0,8900.0,1.0,3.0,0.0,0.0,1085.39,1455.31,560.0,1420.0,254.284,1086.0,224.408299,53.030488,35.124028,778.393466,90031,21.882433

<h3>CoolClimate household 3 Dataset</h3>

In [32]:
coolClimate_household_3 = pd.read_csv("../../data/coolclimate-api-CAzips-size3households-withzc.csv")
X = coolClimate_household_3[['input_income', 'input_footprint_transportation_num_vehicles', 'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_3['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_3 = data
coolClimate_household_3.head()

coolClimate_household_3['input_footprint_transportation_mpg1'].value_counts()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

22.0    1119
Name: input_footprint_transportation_mpg1, dtype: int64

<h3>CoolClimate household 4 Dataset</h3>

In [33]:
coolClimate_household_4 = pd.read_csv("../../data/coolclimate-api-CAzips-size4households-withzc.csv")
X = coolClimate_household_4[['input_income', 'input_footprint_transportation_num_vehicles', 
                             'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 
                             'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 
                             'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 
                             'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 
                             'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 
                             'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 
                             'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 
                             'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_4['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_4 = data
coolClimate_household_4.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,1.0,3.0,22.0,9500.0,1.0,4.0,0.0,0.0,1085.39,1455.31,970.0,1993.0,500.0,1900.0,507.744692,114.824344,165.797795,1902.346653,90001.0,45.573388
1,1.0,3.0,22.0,9300.0,1.0,4.0,0.0,0.0,1085.39,1455.31,1040.0,1993.0,500.0,1900.0,483.411896,110.591039,155.048015,1846.629125,90002.0,45.292999
2,1.0,3.0,22.0,8800.0,1.0,4.0,0.0,0.0,1085.39,1455.31,1000.0,1993.0,500.0,1900.0,472.346716,108.719270,150.318439,1824.279598,90003.0,44.091232
3,1.0,3.0,22.0,8000.0,1.0,1.0,2.0,0.0,1085.39,1455.31,740.0,1993.0,500.0,1900.0,400.265347,102.243626,136.595114,1998.460783,90004.0,42.742324
4,1.0,3.0,22.0,6600.0,1.0,3.0,1.0,0.0,1085.39,1455.31,640.0,1993.0,500.0,1900.0,363.491843,93.488765,113.305066,1782.411632,90005.0,38.714965

<h3>CoolClimate household 5 Dataset</h3>

In [34]:
coolClimate_household_5 = pd.read_csv("../../data/coolclimate-api-CAzips-size5households-withzc.csv")
X = coolClimate_household_5[['input_income', 'input_footprint_transportation_num_vehicles', 
                             'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 
                             'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 
                             'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 
                             'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 
                             'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 
                             'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 
                             'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 
                             'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_5['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_5 = data
coolClimate_household_5.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,1.0,3.0,22.0,9900.0,1.0,0.0,1.0,0.0,1085.39,1455.31,1050.0,1993.0,543.0,2307.0,537.479383,116.992999,178.195998,1883.647175,90001.0,48.752482
1,1.0,3.0,22.0,9700.0,1.0,0.0,1.0,0.0,1085.39,1455.31,1120.0,1993.0,543.0,2307.0,511.721603,112.679741,166.642360,1828.477334,90002.0,48.464335
2,1.0,3.0,22.0,9200.0,1.0,0.0,1.0,0.0,1085.39,1455.31,1070.0,1993.0,543.0,2307.0,500.008420,110.772620,161.559111,1806.347495,90003.0,47.287915
3,1.0,3.0,22.0,8400.0,1.0,0.0,0.0,1.0,1085.39,1455.31,790.0,1993.0,543.0,2307.0,423.705801,104.174673,146.809569,1978.816533,90004.0,45.700226
4,1.0,3.0,22.0,6900.0,1.0,6.0,0.0,0.0,1085.39,1455.31,690.0,1993.0,543.0,2307.0,384.778757,95.254462,121.777913,1764.891079,90005.0,41.577562

<h3>CoolClimate household 1 Dataset TEXAS</h3>

In [35]:
coolClimate_household_1_tx = pd.read_csv('../../data/coolclimate-api-TXzips-size1households-withzc.csv')
X = coolClimate_household_1_tx[['input_income', 'input_footprint_transportation_num_vehicles', 
                             'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 
                             'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 
                             'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 
                             'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 
                             'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 
                             'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 
                             'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 
                             'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_1_tx['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_1_tx = data
coolClimate_household_1_tx.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,2.0,1.0,22.0,6100.0,1.0,1.0,1.0,0.0,2283.87,2705.87,360.0,1420.0,123.001,543.0,101.704950,31.750950,118.497107,751.639358,75001.0,15.651326
1,2.0,1.0,22.0,11000.0,1.0,5.0,0.0,0.0,2237.46,2736.34,700.0,1420.0,123.001,543.0,148.636092,41.505825,176.331578,917.573944,75002.0,22.073460
2,2.0,1.0,22.0,7400.0,1.0,4.0,0.0,0.0,2283.87,2705.87,510.0,1420.0,123.001,543.0,118.361722,33.497685,127.273626,718.006534,75006.0,17.382060
3,2.0,1.0,22.0,9400.0,1.0,5.0,0.0,0.0,2283.87,2705.87,630.0,1420.0,123.001,543.0,141.073743,39.716354,165.521838,879.091485,75007.0,20.480006
4,2.0,1.0,22.0,10500.0,1.0,0.0,1.0,0.0,2189.13,2989.81,650.0,1420.0,123.001,543.0,121.822310,34.011557,130.131516,719.161984,75009.0,20.042413

<h3>CoolClimate household 2 Dataset TEXAS</h3>

In [28]:
coolClimate_household_2_tx = pd.read_csv('../../data/coolclimate-api-TXzips-size2households-withzc.csv')
X = coolClimate_household_2_tx[['input_income', 'input_footprint_transportation_num_vehicles', 
                             'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 
                             'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 
                             'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 
                             'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 
                             'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 
                             'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 
                             'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 
                             'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_2_tx['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_2_tx = data
coolClimate_household_2_tx.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,2.0,1.0,22.0,11300.0,1.0,6.0,1.0,0.0,2283.87,2705.87,700.0,1420.0,254.284,1086.0,212.331032,61.614056,47.789667,1248.402068,75001.0,28.658451
1,2.0,1.0,22.0,20300.0,1.0,3.0,0.0,1.0,2237.46,2736.34,1380.0,1420.0,254.284,1086.0,310.309917,80.543801,71.114203,1524.003763,75002.0,40.880422
2,2.0,1.0,22.0,13700.0,1.0,1.0,2.0,0.0,2283.87,2705.87,1000.0,1420.0,254.284,1086.0,247.105637,65.003668,51.329221,1192.541121,75006.0,31.994302
3,2.0,1.0,22.0,17300.0,1.0,0.0,3.0,0.0,2283.87,2705.87,1240.0,1420.0,254.284,1086.0,294.521881,77.071259,66.754655,1460.088028,75007.0,37.786052
4,2.0,1.0,22.0,19400.0,1.0,0.0,0.0,1.0,2189.13,2989.81,1270.0,1420.0,254.284,1086.0,254.330361,66.000859,52.481802,1194.460215,75009.0,36.923469

<h3>CoolClimate household 3 Dataset TEXAS</h3>

In [10]:
coolClimate_household_3_tx = pd.read_csv('../../data/coolclimate-api-TXzips-size3households-withzc.csv')
X = coolClimate_household_3_tx[['input_income', 'input_footprint_transportation_num_vehicles', 
                             'input_footprint_transportation_mpg1', 'input_footprint_transportation_miles1', 
                             'input_footprint_transportation_fuel1', 'input_footprint_transportation_airshort', 
                             'input_footprint_transportation_airmedium','input_footprint_transportation_airlong', 
                             'input_footprint_housing_cdd', 'input_footprint_housing_hdd', 'input_footprint_housing_electricity_dollars', 
                             'input_footprint_housing_squarefeet', 'input_footprint_housing_watersewage', 
                             'input_footprint_shopping_food_meatfisheggs_default', 'input_footprint_shopping_goods_clothing', 
                             'input_footprint_shopping_goods_other_personalcare', 'input_footprint_shopping_services_education', 
                             'input_footprint_shopping_services_total', 'Zip Code']]
y = coolClimate_household_3_tx['result_grand_total']
labels = X[X.isna().any(axis=1)].index.values
newX = X.dropna(axis = 0, how = 'any')
newy = y.drop(labels, axis = 0)
data = newX
data['result_grand_total'] = newy

coolClimate_household_3_tx = data
coolClimate_household_3_tx.head()

/Users/junkang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,Zip Code,result_grand_total
0,2.0,1.0,22.0,10600.0,1.0,0.0,3.0,0.0,2283.87,2705.87,810.0,1420.0,315.0,1493.0,153.499669,45.098635,102.733048,1069.840733,75001.0,29.857623
1,2.0,1.0,22.0,18800.0,1.0,4.0,0.0,1.0,2237.46,2736.34,1600.0,1420.0,315.0,1493.0,224.331174,58.954331,152.873610,1306.022591,75002.0,41.900855
2,2.0,1.0,22.0,12800.0,1.0,5.0,1.0,0.0,2283.87,2705.87,1150.0,1420.0,315.0,1493.0,178.639144,47.579674,110.341998,1021.969684,75006.0,33.283102
3,2.0,1.0,22.0,16100.0,1.0,1.0,3.0,0.0,2283.87,2705.87,1440.0,1420.0,315.0,1493.0,212.917589,56.412591,143.501925,1251.248846,75007.0,38.930826
4,2.0,1.0,22.0,18000.0,1.0,8.0,0.0,0.0,2189.13,2989.81,1480.0,1420.0,315.0,1493.0,183.862086,48.309571,112.819694,1023.614287,75009.0,38.274241

<h3>Concatenated CoolClimate Datasets</h3>

In [36]:
coolClimate = pd.concat([coolClimate_household_1, coolClimate_household_2, coolClimate_household_3, coolClimate_household_4,
                        coolClimate_household_5, coolClimate_household_1_tx, coolClimate_household_2_tx, coolClimate_household_3_tx])
coolClimate.head()
coolClimate.shape

(9502, 20)

In [37]:
coolClimate['Zip Code'] = coolClimate['Zip Code'].astype('int')

coolClimate['Zip Code']

coolClimate = coolClimate.rename(columns={'Zip Code': 'ZipCode'})

coolClimate.head()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,ZipCode,result_grand_total
0,1.0,1.0,22.0,8700.0,1.0,2.0,0.0,0.0,1085.39,1455.31,470.0,1591.0,237.0,543.0,169.350149,47.227769,55.002939,963.524289,90001,18.998752
1,1.0,1.0,22.0,8500.0,1.0,2.0,0.0,0.0,1085.39,1455.31,510.0,1591.0,237.0,543.0,161.234333,45.486592,51.436731,935.303780,90002,18.960587
2,1.0,1.0,22.0,8000.0,1.0,2.0,0.0,0.0,1085.39,1455.31,490.0,1591.0,237.0,543.0,157.543718,44.716724,49.867708,923.983913,90003,18.488686
3,1.0,1.0,22.0,7300.0,1.0,1.0,1.0,0.0,1085.39,1455.31,360.0,1591.0,237.0,543.0,133.502127,42.053263,45.315034,1012.205374,90004,18.001409
4,1.0,1.0,22.0,6000.0,1.0,4.0,0.0,0.0,1085.39,1455.31,310.0,1591.0,237.0,543.0,121.236910,38.452350,37.588628,902.778103,90005,16.311888

In [38]:
coolClimate_grouped_by = coolClimate.groupby(['ZipCode']).sum()
coolClimate_grouped_by.head()

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,input_footprint_housing_electricity_dollars,input_footprint_housing_squarefeet,input_footprint_housing_watersewage,input_footprint_shopping_food_meatfisheggs_default,input_footprint_shopping_goods_clothing,input_footprint_shopping_goods_other_personalcare,input_footprint_shopping_services_education,input_footprint_shopping_services_total,result_grand_total
ZipCode,,,,,,,,,,,,,,,,,,,
75001,15.0,6.0,88.0,40200.0,4.0,14.0,7.0,1.0,9135.48,10823.48,2930.0,6253.0,1169.285,4615.0,872.025234,258.423082,482.535033,6368.974181,132.345006
75002,15.0,6.0,88.0,71800.0,4.0,21.0,0.0,4.0,8949.84,10945.36,5760.0,6253.0,1169.285,4615.0,1274.416067,337.818651,718.044230,7775.011646,188.875142
75006,6.0,3.0,66.0,33900.0,3.0,10.0,3.0,0.0,6851.61,8117.61,2660.0,4260.0,692.285,3122.0,544.106503,146.081027,288.944845,2932.517339,82.659464
75007,15.0,6.0,88.0,61400.0,4.0,14.0,6.0,2.0,9135.48,10823.48,5190.0,6253.0,1169.285,4615.0,1209.575965,323.254035,674.025617,7448.932672,174.514741
75009,15.0,6.0,88.0,68700.0,4.0,10.0,1.0,3.0,8756.52,11959.24,5320.0,6253.0,1169.285,4615.0,1044.512859,276.822311,529.911801,6093.778970,170.518617

In [39]:
jonesKammen_ca_zipcode = jonesKammen_ca_zipcode.drop(columns=["Latitude", "Longitude", "Elevation", "State", "StateFullName", 
                                    "City", "CBSAType", "CBSAName","MSAName", "PMSA_Name", "Region", 
                                    "Division", "Transport (tCO2e/yr)", "Housing (tCO2e/yr)", "Food (tCO2e/yr)",
                                    "Goods (tCO2e/yr)", "Services (tCO2e/yr)", 
                                     "Total Household Carbon Footprint (tCO2e/yr)", "Total Zip Code Carbon Footprint (tCO2e/yr)"])
jonesKammen_ca_zipcode.head()

,ZipCode,Population,PersonsPerHousehold,AverageHouseValue,IncomePerHousehold,CountyName,popden,electricity (kWh),Nat. Gas (cu.ft.),FUELOIL (gallons),Vehicle miles traveled,HouseholdsPerZipCode
24736,75001,8259,1.67,211500,57064,DALLAS,2577.877881,7837.995768,19659.345436,0.000000,19940,5298
24737,75002,37216,3.04,134600,74144,COLLIN,946.058546,15468.947840,36235.564581,0.000000,35597,12643
24738,75006,46784,2.74,113100,52798,DALLAS,2671.018033,11159.270011,29917.724715,0.000000,24155,17623
24739,75007,49933,2.88,127500,70081,DENTON,4173.677056,13940.502644,35042.459562,0.182369,30477,17652
24740,75009,4951,2.88,114400,52821,COLLIN,51.653956,14274.824867,30800.902746,0.710305,34030,1854

In [40]:
mergedZC = coolClimate_grouped_by.join(jonesKammen_ca_zipcode.set_index('ZipCode'))
mergedZC

,input_income,input_footprint_transportation_num_vehicles,input_footprint_transportation_mpg1,input_footprint_transportation_miles1,input_footprint_transportation_fuel1,input_footprint_transportation_airshort,input_footprint_transportation_airmedium,input_footprint_transportation_airlong,input_footprint_housing_cdd,input_footprint_housing_hdd,...,PersonsPerHousehold,AverageHouseValue,IncomePerHousehold,CountyName,popden,electricity (kWh),Nat. Gas (cu.ft.),FUELOIL (gallons),Vehicle miles traveled,HouseholdsPerZipCode
ZipCode,,,,,,,,,,,,,,,,,,,,,
75001,15.0,6.0,88.0,40200.0,4.0,14.0,7.0,1.0,9135.4800,10823.48,...,1.67,211500,57064,DALLAS,2577.877881,7837.995768,19659.345436,0.000000,19940,5298
75002,15.0,6.0,88.0,71800.0,4.0,21.0,0.0,4.0,8949.8400,10945.36,...,3.04,134600,74144,COLLIN,946.058546,15468.947840,36235.564581,0.000000,35597,12643
75006,6.0,3.0,66.0,33900.0,3.0,10.0,3.0,0.0,6851.6100,8117.61,...,2.74,113100,52798,DALLAS,2671.018033,11159.270011,29917.724715,0.000000,24155,17623
75007,15.0,6.0,88.0,61400.0,4.0,14.0,6.0,2.0,9135.4800,10823.48,...,2.88,127500,70081,DENTON,4173.677056,13940.502644,35042.459562,0.182369,30477,17652
75009,15.0,6.0,88.0,68700.0,4.0,10.0,1.0,3.0,8756.5200,11959.24,...,2.88,114400,52821,COLLIN,51.653956,14274.824867,30800.902746,0.710305,34030,1854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96145,38.0,16.0,154.0,67800.0,7.0,30.0,8.0,4.0,442.0598,56980.00,...,2.26,381000,54545,PLACER,229.022614,6827.537009,64632.700888,0.000000,16259,4543
96146,27.0,13.0,132.0,63600.0,6.0,45.0,5.0,1.0,378.9084,48840.00,...,2.29,597500,64000,PLACER,34.115020,6067.546802,32796.048395,64.929993,18836,1179
96148,37.0,16.0,154.0,76400.0,7.0,18.0,7.0,3.0,442.0598,56980.00,...,2.72,361500,43859,PLACER,1682.066755,5848.892717,55434.423182,0.000000,19188,425
96150,36.0,16.0,154.0,64200.0,7.0,13.0,9.0,3.0,1306.6270,52971.87,...,2.52,169000,40076,EL DORADO,121.760078,6375.163154,63824.381593,1.115923,17145,20536
96161,29.0,14.0,154.0,77800.0,7.0,21.0,6.0,3.0,1406.1530,49387.24,...,2.67,247800,58113,NEVADA,63.879702,7060.381641,48060.302222,9.352292,20130,12406

In [41]:
final_dataset = mergedZC.groupby(['CountyName']).sum()
final_dataset = final_dataset.drop(columns=["input_income", 
                                            'input_footprint_transportation_mpg1',
                                            'input_footprint_transportation_fuel1',
                                            'input_footprint_housing_cdd',
                                            'input_footprint_housing_hdd',
                                            'input_footprint_housing_watersewage',
                                            'input_footprint_shopping_goods_other_personalcare',
                                            'input_footprint_shopping_services_education',
                                            'input_footprint_shopping_services_total',
                                            'input_footprint_shopping_food_meatfisheggs_default'
                                           ])

In [42]:
final_dataset = final_dataset.rename({'input_footprint_transportation_num_vehicles': 'num_vehicles',
                                     'input_footprint_transportation_miles1': 'miles_traveled_year',
                                     'input_footprint_transportation_airshort': 'num_short_flights',
                                     'input_footprint_transportation_airmedium': 'num_med_flights',
                                     'input_footprint_transportation_airlong': 'num_long_flights',
                                     'input_footprint_housing_electricity_dollars': 'electricity_billPerYear',
                                      'input_footprint_housing_squarefeet': 'housing_squarefeet',
                                      'input_footprint_shopping_goods_clothing': 'moneySpentOnClothesPerYear'
                                     },
                                     
                                     axis = 1)


final_dataset

,num_vehicles,miles_traveled_year,num_short_flights,num_med_flights,num_long_flights,electricity_billPerYear,housing_squarefeet,moneySpentOnClothesPerYear,result_grand_total,Population,PersonsPerHousehold,AverageHouseValue,IncomePerHousehold,popden,electricity (kWh),Nat. Gas (cu.ft.),FUELOIL (gallons),Vehicle miles traveled,HouseholdsPerZipCode
CountyName,,,,,,,,,,,,,,,,,,,
ALAMEDA,242.0,1613500.0,483.0,126.0,89.0,97190.0,211948.5,40510.762336,5277.395845,1333498,111.87,13884600,2590891,258994.046896,275913.455348,1.768720e+06,22.368750,983886,505952
ALPINE,15.0,86300.0,27.0,8.0,3.0,5440.0,14048.0,2366.563071,295.877796,1071,6.22,1177601,84191,5.789275,11596.212856,5.219063e+04,28.795106,34414,1002
AMADOR,87.0,700100.0,162.0,39.0,27.0,37630.0,71966.0,14149.849255,2018.848980,35248,24.21,1578400,442394,2747.175496,68394.867629,2.955696e+05,14.518174,284242,15061
ANDERSON,18.0,170100.0,23.0,15.0,3.0,12330.0,20055.0,2377.138345,426.297154,56985,12.88,302700,164792,217.132534,56492.456566,1.269573e+05,4.450502,128037,19401
ANDREWS,11.0,60700.0,3.0,1.0,6.0,5610.0,7993.0,1319.917126,221.874511,12985,2.81,42500,34086,12.306216,11292.014844,3.320776e+04,0.000000,26524,5391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YOLO,86.0,729100.0,156.0,47.0,19.0,40840.0,75567.5,15685.007927,2039.451539,168755,37.58,2247700,568373,5443.151339,92361.707141,4.603712e+05,53.302067,356259,61576
YOUNG,25.0,173200.0,30.0,10.0,3.0,15280.0,20781.0,2958.539090,527.543869,18516,11.97,212300,141375,56.766915,57838.070899,1.546128e+05,25.937962,130096,9272
YUBA,94.0,687500.0,138.0,20.0,6.0,38030.0,75954.5,12315.845246,1862.989227,59625,30.36,1319000,361731,3266.749110,74782.773304,3.831926e+05,36.485245,298695,22383
ZAPATA,5.0,35900.0,15.0,1.0,0.0,3730.0,5691.0,724.148279,112.065122,12150,3.10,46300,24596,17.458331,12610.302432,2.271334e+04,0.986334,20255,6100
ZAVALA,10.0,55300.0,11.0,0.0,0.0,5340.0,8406.5,1026.716192,172.966006,10023,6.70,45500,34269,36.607646,20740.833593,4.718235e+04,6.585109,39447,3464

In [43]:
final_dataset.to_csv('../../data/jonesKammen-PlUS-CoolClimate.csv')