In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
ca_ghg = pd.read_csv('../../data/ghg_sector_data.csv', skiprows=9)
ca_ghg.head()

,Inventory Accountin,Main Sector,Sub Sector Level 1,Sub Sector Level 2,Sub Sector Level 3,Main Activity,Activity Subset,GHG,2000,2001,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Coal,CH4,0.000017,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
1,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Coal,CO2,0.005791,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
2,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Coal,N2O,0.000030,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
3,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Distillate,CH4,0.000067,0.0000845500,...,0.0001418375,0.0000604650,0.0000454875,0.0000257825,0.0000382750,0.0000388550,0.0000331825,0.0000312375,0.0000226550,0.0000276750
4,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Distillate,CO2,0.066414,0.0833767351,...,0.1398696019,0.0596262562,0.0448574796,0.0254243417,0.0377435630,0.0383151259,0.0327219749,0.0308031566,0.0223419847,0.0272921275

In [15]:
ca_co2 = ca_ghg[ca_ghg['GHG'] == 'CO2']
ca_co2.head()

,Inventory Accountin,Main Sector,Sub Sector Level 1,Sub Sector Level 2,Sub Sector Level 3,Main Activity,Activity Subset,GHG,2000,2001,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Coal,CO2,0.005791,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
4,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Distillate,CO2,0.066414,0.0833767351,...,0.1398696019,0.0596262562,0.0448574796,0.0254243417,0.0377435630,0.0383151259,0.0327219749,0.0308031566,0.0223419847,0.0272921275
7,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Kerosene,CO2,0.119672,0.1492445520,...,0.0731350080,0.0613485360,0.0469936080,0.0202024800,0.0193294080,0.0250957440,0.0186289200,0.0355827600,0.0215730000,0.0215730000
10,Included,Residential,Household Use,Not Specified,None,Fuel combustion,LPG,CO2,1.126649,0.7733314200,...,1.9011142800,1.9980405000,1.8936196600,1.4314094400,1.4372665800,1.1842759200,1.3304525000,1.4489178800,1.3916060800,1.5164324400
13,Included,Residential,Household Use,Not Specified,None,Fuel combustion,Natural gas,CO2,27.947372,27.3511623000,...,26.2331692900,26.9571578400,27.4865146700,25.7327083500,26.4989291800,21.5621198600,21.8747495700,22.7750129800,23.5917927600,23.2019419000